package com.tadmor.domain.model

/**
 * IAU-approved proper names for exoplanets and their host stars from the
 * NameExoWorlds campaigns (2015, 2019, 2022). Keys are the standard
 * designation as used in the NASA Exoplanet Archive.
 */
object ProperNames {

    // ═══════════════════════════════════════════
    // Star names (hostname → IAU proper name)
    // ═══════════════════════════════════════════

    private val starNames: Map<String, String> = mapOf(
        // NameExoWorlds 2015
        "14 And" to "Veritate",
        "18 Del" to "Musica",
        "42 Dra" to "Fafnir",
        "47 UMa" to "Chalawan",
        "51 Peg" to "Helvetios",
        "55 Cnc" to "Copernicus",
        "HD 104985" to "Tonatiuh",
        "HD 149026" to "Ogma",
        "HD 81688" to "Intercrus",
        "eps Eri" to "Ran",
        "mu Ara" to "Cervantes",
        "ups And" to "Titawin",
        "xi Aql" to "Libertas",
        "gam Cep" to "Errai",
        "iot Dra" to "Edasich",
        "PSR B1257+12" to "Lich",
        "PSR 1257+12" to "Lich",

        // Pre-existing IAU star names (exoplanet hosts)
        "bet Gem" to "Pollux",
        "alf PsA" to "Fomalhaut",
        "eps Tau" to "Ain",

        // NameExoWorlds 2019
        "8 UMi" to "Baekdu",
        "BD+14 4559" to "Solaris",
        "BD-17 63" to "Felixvarela",
        "HAT-P-2" to "Hunor",
        "HAT-P-3" to "Dombay",
        "HAT-P-5" to "Chasoň",
        "HAT-P-6" to "Sterrennacht",
        "HAT-P-9" to "Tevel",
        "HAT-P-14" to "Franz",
        "HAT-P-15" to "Berehynia",
        "HAT-P-21" to "Mazaalai",
        "HAT-P-23" to "Moriah",
        "HAT-P-29" to "Muspelheim",
        "HAT-P-34" to "Sansuna",
        "HAT-P-36" to "Tuiren",
        "HAT-P-38" to "Horna",
        "HAT-P-40" to "Taika",
        "HAT-P-42" to "Lerna",
        "HIP 12961" to "Koeia",
        "HIP 79431" to "Sharjah",
        "HD 1502" to "Citadelle",
        "HD 4208" to "Cocibolca",
        "HD 6434" to "Nenque",
        "HD 7199" to "Emiw",
        "HD 8574" to "Bélénos",
        "HD 16175" to "Buna",
        "HD 17156" to "Nushagak",
        "HD 18742" to "Ayeyarwady",
        "HD 20868" to "Intan",
        "HD 23079" to "Tupi",
        "HD 28678" to "Hoggar",
        "HD 30856" to "Mouhoun",
        "HD 32518" to "Mago",
        "HD 38283" to "Bubup",
        "HD 43197" to "Amadioha",
        "HD 45350" to "Lucilinburhuc",
        "HD 45652" to "Lusitânia",
        "HD 48265" to "Nosaxa",
        "HD 49674" to "Nervia",
        "HD 52265" to "Citalá",
        "HD 63454" to "Ceibo",
        "HD 63765" to "Tapecue",
        "HD 68988" to "Násti",
        "HD 73534" to "Gakyid",
        "HD 75898" to "Stribor",
        "HD 82886" to "Illyrian",
        "HD 83443" to "Kalausi",
        "HD 85390" to "Natasha",
        "HD 86081" to "Bibhā",
        "HD 93083" to "Macondo",
        "HD 96063" to "Dingolay",
        "HD 98219" to "Hunahpú",
        "HD 99109" to "Shama",
        "HD 100655" to "Formosa",
        "HD 100777" to "Sagarmatha",
        "HD 102117" to "Uklun",
        "HD 102195" to "Flegetonte",
        "HD 102956" to "Aniara",
        "HD 108147" to "Tupã",
        "HD 109246" to "Funi",
        "HD 117618" to "Dofida",
        "HD 118203" to "Liesma",
        "HD 130322" to "Mönch",
        "HD 131496" to "Arcalís",
        "HD 136418" to "Nikawiy",
        "HD 137388" to "Karaka",
        "HD 145457" to "Kamuy",
        "HD 148427" to "Timir",
        "HD 149143" to "Rosalíadecastro",
        "HD 152581" to "Mahsati",
        "HD 153950" to "Rapeto",
        "HD 156411" to "Inquill",
        "HD 164604" to "Pincoya",
        "HD 168746" to "Alasia",
        "HD 173416" to "Xihe",
        "HD 175541" to "Kaveh",
        "HD 179949" to "Gumala",
        "HD 181342" to "Belel",
        "HD 181720" to "Sika",
        "HD 192263" to "Phoenicia",
        "HD 192699" to "Chechia",
        "HD 205739" to "Sāmaya",
        "HD 206610" to "Bosona",
        "HD 208487" to "Itonda",
        "HD 212771" to "Lionrock",
        "HD 218566" to "Ebla",
        "HD 221287" to "Poerava",
        "HD 224693" to "Axólotl",
        "HD 231701" to "Uruk",
        "WASP-6" to "Márohu",
        "WASP-13" to "Gloas",
        "WASP-15" to "Nyamien",
        "WASP-17" to "Dìwö",
        "WASP-21" to "Tangra",
        "WASP-22" to "Tojil",
        "WASP-32" to "Parumleo",
        "WASP-34" to "Amansinaya",
        "WASP-38" to "Irena",
        "WASP-39" to "Malmok",
        "WASP-50" to "Chaophraya",
        "WASP-52" to "Anadolu",
        "WASP-60" to "Morava",
        "WASP-62" to "Naledi",
        "WASP-64" to "Atakoraka",
        "WASP-71" to "Mpingo",
        "WASP-72" to "Diya",
        "WASP-79" to "Montuno",
        "WASP-80" to "Petra",
        "WASP-161" to "Tislit",
        "XO-1" to "Moldoveanu",
        "XO-4" to "Koit",
        "XO-5" to "Absolutno",
        "TrES-3" to "Pipoltr",

        // NameExoWorlds 2022 (JWST targets)
        "GJ 367" to "Añañuca",
        "GJ 436" to "Noquisi",
        "GJ 486" to "Gar",
        "GJ 1214" to "Orkaria",
        "GJ 3470" to "Kaewkosin",
        "HAT-P-12" to "Komondor",
        "HAT-P-26" to "Guahayona",
        "HATS-72" to "Zembra",
        "HIP 65426" to "Matza",
        "HD 95086" to "Aiolos",
        "L 168-9" to "Danfeng",
        "LHS 3844" to "Batsũ̀",
        "LTT 9779" to "Uúba",
        "WASP-19" to "Wattle",
        "WASP-43" to "Gnomon",
        "WASP-63" to "Kosjenka",
        "WASP-69" to "Wouri",
        "WASP-121" to "Dilmun",
        "WASP-166" to "Filetdor",
        "WD 0806-661" to "Maru",
    )

    // ═══════════════════════════════════════════
    // Planet names (pl_name → IAU proper name)
    // ═══════════════════════════════════════════

    private val planetNames: Map<String, String> = mapOf(
        // NameExoWorlds 2015 (19 systems, 31 planets)
        "14 And b" to "Spe",
        "18 Del b" to "Arion",
        "42 Dra b" to "Orbitar",
        "47 UMa b" to "Taphao Thong",
        "47 UMa c" to "Taphao Kaew",
        "51 Peg b" to "Dimidium",
        "55 Cnc b" to "Galileo",
        "55 Cnc c" to "Brahe",
        "55 Cnc d" to "Lipperhey",
        "55 Cnc e" to "Janssen",
        "55 Cnc f" to "Harriot",
        "eps Eri b" to "AEgir",
        "eps Tau b" to "Amateru",
        "xi Aql b" to "Fortitudo",
        "HD 104985 b" to "Meztli",
        "HD 149026 b" to "Smertrios",
        "HD 81688 b" to "Arkas",
        "mu Ara b" to "Quijote",
        "mu Ara c" to "Dulcinea",
        "mu Ara d" to "Rocinante",
        "mu Ara e" to "Sancho",
        "PSR 1257+12 b" to "Draugr",
        "PSR 1257+12 c" to "Poltergeist",
        "PSR 1257+12 d" to "Phobetor",
        "PSR B1257+12 b" to "Draugr",
        "PSR B1257+12 c" to "Poltergeist",
        "PSR B1257+12 d" to "Phobetor",
        "ups And b" to "Saffar",
        "ups And c" to "Samh",
        "ups And d" to "Majriti",
        "gam Cep b" to "Tadmor",
        "alf PsA b" to "Dagon",
        "Fomalhaut b" to "Dagon",
        "iot Dra b" to "Hypatia",
        "bet Gem b" to "Thestias",
        "Pollux b" to "Thestias",
        "BD-17 63 b" to "Finlay",
        "BD+14 4559 b" to "Pirx",

        // NameExoWorlds 2019 (112 planets, one per IAU member country)
        "8 UMi b" to "Halla",
        "HAT-P-2 b" to "Magor",
        "HAT-P-3 b" to "Teberda",
        "HAT-P-5 b" to "Kráľomoc",
        "HAT-P-6 b" to "Nachtwacht",
        "HAT-P-9 b" to "Alef",
        "HAT-P-14 b" to "Sissi",
        "HAT-P-15 b" to "Tryzub",
        "HAT-P-21 b" to "Bambaruush",
        "HAT-P-23 b" to "Jebus",
        "HAT-P-29 b" to "Surt",
        "HAT-P-34 b" to "Ġgantija",
        "HAT-P-36 b" to "Bran",
        "HAT-P-38 b" to "Hiisi",
        "HAT-P-40 b" to "Vytis",
        "HAT-P-42 b" to "Iolaus",
        "HIP 12961 b" to "Aumatex",
        "HIP 79431 b" to "Barajeel",
        "HD 1502 b" to "Indépendance",
        "HD 4208 b" to "Xolotlan",
        "HD 6434 b" to "Eyeke",
        "HD 7199 b" to "Hairu",
        "HD 8574 b" to "Bélisama",
        "HD 16175 b" to "Abol",
        "HD 17156 b" to "Mulchatna",
        "HD 18742 b" to "Bagan",
        "HD 20868 b" to "Baiduri",
        "HD 23079 b" to "Guarani",
        "HD 28678 b" to "Tassili",
        "HD 30856 b" to "Nakanbé",
        "HD 32518 b" to "Neri",
        "HD 33844 b" to "Timir",
        "HD 33844 c" to "Samagiya",
        "HD 38283 b" to "Yanyan",
        "HD 43197 b" to "Equiano",
        "HD 45350 b" to "Peitruss",
        "HD 45652 b" to "Viriato",
        "HD 48265 b" to "Naqaỹa",
        "HD 49674 b" to "Eburonia",
        "HD 52265 b" to "Cayahuanca",
        "HD 63454 b" to "Ibirapitá",
        "HD 63765 b" to "Yvaga",
        "HD 68988 b" to "Albmi",
        "HD 73534 b" to "Drukyul",
        "HD 75898 b" to "Veles",
        "HD 82886 b" to "Arber",
        "HD 83443 b" to "Buru",
        "HD 85390 b" to "Madalitso",
        "HD 86081 b" to "Santamasa",
        "HD 93083 b" to "Melquíades",
        "HD 96063 b" to "Ramajay",
        "HD 98219 b" to "Ixbalanqué",
        "HD 99109 b" to "Perwana",
        "HD 100655 b" to "Sazum",
        "HD 100777 b" to "Laligurans",
        "HD 102117 b" to "Leklsullun",
        "HD 102195 b" to "Lete",
        "HD 102956 b" to "Isagel",
        "HD 108147 b" to "Tumearandu",
        "HD 109246 b" to "Fold",
        "HD 117618 b" to "Noifasui",
        "HD 118203 b" to "Staburags",
        "HD 130322 b" to "Eiger",
        "HD 131496 b" to "Madriu",
        "HD 136418 b" to "Awasis",
        "HD 137388 b" to "Kererū",
        "HD 145457 b" to "Chura",
        "HD 148427 b" to "Tondra",
        "HD 149143 b" to "Riosar",
        "HD 152581 b" to "Ganja",
        "HD 153950 b" to "Trimobe",
        "HD 156411 b" to "Sumajmajta",
        "HD 164604 b" to "Caleuche",
        "HD 168746 b" to "Onasilos",
        "HD 173416 b" to "Wangshu",
        "HD 175541 b" to "Kavian",
        "HD 179949 b" to "Mastika",
        "HD 181342 b" to "Dopere",
        "HD 181720 b" to "Toge",
        "HD 192263 b" to "Beirut",
        "HD 192699 b" to "Khomsa",
        "HD 205739 b" to "Samagiya",
        "HD 206610 b" to "Naron",
        "HD 208487 b" to "Mintome",
        "HD 212771 b" to "Victoriapeak",
        "HD 218566 b" to "Ugarit",
        "HD 221287 b" to "Pipitea",
        "HD 224693 b" to "Xólotl",
        "HD 231701 b" to "Babylonia",
        "WASP-6 b" to "Boinayel",
        "WASP-13 b" to "Cruinlagh",
        "WASP-15 b" to "Asye",
        "WASP-17 b" to "Ditsö̀",
        "WASP-21 b" to "Bendida",
        "WASP-22 b" to "Koyopa'",
        "WASP-32 b" to "Viculus",
        "WASP-34 b" to "Haik",
        "WASP-38 b" to "Iztok",
        "WASP-39 b" to "Bocaprins",
        "WASP-50 b" to "Maeping",
        "WASP-52 b" to "Göktürk",
        "WASP-60 b" to "Vlasina",
        "WASP-62 b" to "Krotoa",
        "WASP-64 b" to "Agouto",
        "WASP-71 b" to "Tanzanite",
        "WASP-72 b" to "Cuptor",
        "WASP-79 b" to "Pollera",
        "WASP-80 b" to "Wadirum",
        "WASP-161 b" to "Isli",
        "XO-1 b" to "Negoiu",
        "XO-4 b" to "Hämarik",
        "XO-5 b" to "Makropulos",
        "TrES-3 b" to "Umbäässa",

        // NameExoWorlds 2022 (JWST targets)
        "GJ 367 b" to "Tahay",
        "GJ 436 b" to "Awohali",
        "GJ 486 b" to "Su",
        "GJ 1214 b" to "Enaiposha",
        "GJ 3470 b" to "Phailinsiam",
        "HAT-P-12 b" to "Puli",
        "HAT-P-26 b" to "Guataubá",
        "HATS-72 b" to "Zembretta",
        "HIP 65426 b" to "Najsakopajk",
        "HD 95086 b" to "Levantes",
        "L 168-9 b" to "Qingluan",
        "LHS 3844 b" to "Kua'kua",
        "LTT 9779 b" to "Cuancoá",
        "WASP-19 b" to "Banksia",
        "WASP-43 b" to "Astrolábos",
        "WASP-63 b" to "Regoč",
        "WASP-69 b" to "Makombé",
        "WASP-121 b" to "Tylos",
        "WASP-166 b" to "Catalineta",
        "WD 0806-661 b" to "Ahra",
        "WD 0806-661 B" to "Ahra",
    )

    /** Look up the IAU proper name for a planet designation. */
    fun forPlanet(designation: String): String? = planetNames[designation]

    /** Look up the IAU proper name for a star hostname. */
    fun forStar(hostname: String): String? = starNames[hostname]

    /** Find hostnames whose proper star name contains the query (case-insensitive). */
    fun findStarHostnamesByProperName(query: String): List<String> {
        val q = query.lowercase()
        return starNames.entries
            .filter { (_, name) -> name.lowercase().contains(q) }
            .map { (hostname, _) -> hostname }
    }
}
